### PR TITLE
fix: install newrelic.ini into mods-available on Debian/Ubuntu

### LINKED ISSUE #1168: install script does not install in  mods-available folder
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

The install script does not recognize /etc/php/8.4/mods-available/ as the default location to install the newrelic.ini which makes it necessary to manage the fpm and cli ini indipendently.

ubuntu:jammy-20251013

## Description

on ubuntu:jammy-20251013 

## Steps to Reproduce

```
# NR_INSTALL_SILENT=yes ./newrelic-install install
# find / -iname '*newrelic*.ini'
/etc/php/8.4/fpm/conf.d/20-newrelic.ini
/etc/php/8.4/cli/conf.d/20-newrelic.ini

# phpenmod newrelic
WARNING: Module newrelic ini file doesn't exist under /etc/php/8.4/mods-available
WARNING: Module newrelic ini file doesn't exist under /etc/php/8.4/mods-available
# phpdismod newrelic
WARNING: Module newrelic ini file doesn't exist under /etc/php/8.4/mods-available
WARNING: Module newrelic ini file doesn't exist under /etc/php/8.4/mods-available
```
[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
```
# NR_INSTALL_SILENT=yes ./newrelic-install install
# find / -iname '*newrelic*.ini'
/etc/php/8.4/mods-available/newrelic.ini
```

### PR DESCRIPTION
**Pull request by lavarou**
On Debian/Ubuntu systems, the tarball installer placed newrelic.ini directly
into each SAPI's conf.d directory, bypassing the mods-available module
management layout. This made phpenmod/phpdismod unable to manage the newrelic
module.

The installer now detects when a mods-available directory exists, installs
newrelic.ini there, and creates 20-newrelic.ini symlinks in each SAPI's conf.d
directory. This new behavior makes tarball install method consistent with deb
package install method, which is consistent with Debian PHP module conventions.

Fixes #1168

### CODE REVIEW

**Review by ZNeumann — DISMISSED** [review]

File: agent/newrelic-install.sh [hunk 1]
```diff
@@ -1516,6 +1544,28 @@ install_agent_here() {
...
+    for sapi_confdir in ${pi_sapi_confdirs}; do
+      if [ -d "${sapi_confdir}" ]; then
+        if [ ! -e "${sapi_confdir}/newrelic.ini" -a ! -e "${sapi_confdir}/20-newrelic.ini" ]; then
+          if logcmd ln -sf "${pi_mods_avail}/newrelic.ini" "${sapi_confdir}/20-newrelic.ini"; then
+            if [ -z "${NR_INSTALL_SILENT}" ]; then
+              echo "      Install Status : ${sapi_confdir}/20-newrelic.ini symlinked"
+            fi
+            log "${pdir}: created symlink ${sapi_confdir}/20-newrelic.ini -> ${pi_mods_avail}/newrelic.ini"
+          else
+            log "${pdir}: failed to create symlink ${sapi_confdir}/20-newrelic.ini"
```
Comment (mfulb) [inline agent/newrelic-install.sh:1563]: Something to consider - when installing `newrelic.ini` above if this fails then `istat` is set to failed - not sure if that is applicable here as well.

Comment (lavarou) [reply agent/newrelic-install.sh:1563]: https://github.com/newrelic/newrelic-php-agent/pull/1170/commits/e6b117f0b427ba5283391f7a6e930f58dfdbc200

**Review by mfulb — APPROVED** [review]

**Review by ZNeumann — APPROVED** [review]
