### PR TITLE
fix(agent): end guzzle's external segment for rejected request

### LINKED ISSUE #320: Guzzle timeouts are not recognized as externals.
## Description
When using Guzzle 6 to make external calls it was noticed some of the calls are not recognized as externals and it was narrowed down to those that result in timeouts.
## Steps to Reproduce

The following script will cause the issue:

```
<?php
require_once "vendor/autoload.php";

use GuzzleHttp\Promise;
use GuzzleHttp\Client;

$client = new Client();
sleep(3);
$promises = [
    "req1" => $client->getAsync('https://deelay.me/5000/http://www.example.com', ['timeout' => 3]),
    "req2" => $client->getAsync('http://www.google.com')
];

$results = GuzzleHttp\Promise\settle($promises)->wait();

echo $results['req1']['state'] . "\n";
echo $results['req2']['state'] . "\n";
?>
```

The async request "req1" will timeout and the external segment will not show up in the application trace information.

If the delay time passed to "http://deelay.me" is reduced to 500, for example, the "req1" request will show up as an external segment because it completes before the 3 second timeout specified.

## Expected Behavior

A async guzzle request which times out will show up as an external segment with a status representative of the time out and failure for the request to complete.   For example, when a async request with curl_multi time outs the http response status is set to 0.   

## Your Environment

The issue was recreated in the following environment:
Ubuntu 18.04
PHP 7.3.16
guzzle 6.5.5

Issue was reported for a system using:
Ubuntu 18.04
PHP 7.3.16
Guzzle: 6.3.3
cURL version: 7.58.0

### PR DESCRIPTION
**Pull request by lavarou**
Modify the onRejected handler to end guzzle's external segment even when
there's no response. This allows to mark the span as an external span and
capture the uri and method of the request. Additionally when sync requests is
rejected, onRejected callback is not called via `PromiseInterface::then` and
needs to be called manually.

Fixes #320.

### CODE REVIEW

File: daemon/cmd/integration_runner/main.go [hunk 1]
```diff
@@ -375,6 +375,7 @@ func main() {
 
 	// Env vars common to all tests.
 	ctx.Env["EXTERNAL_HOST"] = externalHost
+	os.Setenv("EXTERNAL_HOST", externalHost)
```
Comment (mfulb) [inline daemon/cmd/integration_runner/main.go:378]: Why is it necessary to add this?

File: tests/integration/external/guzzle6/test_timeout_async.php [hunk 2]
```diff
@@ -20,6 +20,9 @@
 newrelic.code_level_metrics.enabled = 0
 */
 
+/*EXPECT_METRICS_EXIST
+External/127.0.0.1/all
```
Comment (mfulb) [inline tests/integration/external/guzzle6/test_timeout_async.php:24]: I'm unclear on why the metric and segment name below would contain "127.0.0.1" as the host but the `http.url` is captured with `ENV[EXTERNAL_HOST]` which I'm guessing is a different value as it necessitated adding support for pulling in env vars for `EXPECT_SPAN_EVENTS_LIKE`.

File: daemon/cmd/integration_runner/main.go (hunk 1 above)
Comment (lavarou) [reply daemon/cmd/integration_runner/main.go:378]: In order to use it in `EXPECT_SPAN_EVENTS_LIKE` [here](https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/tests/integration/external/guzzle7/test_timeout_sync.php#L47).

File: tests/integration/external/guzzle6/test_timeout_async.php (hunk 2 above)
Comment (lavarou) [reply tests/integration/external/guzzle6/test_timeout_async.php:24]: `EXTERNAL_HOST` is set [here](https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/daemon/cmd/integration_runner/main.go#L324) and includes port number, which, unless provided via [`-external_port` flag](https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/daemon/cmd/integration_runner/main.go#L55-L57), is assigned at random (see [here](https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/daemon/cmd/integration_runner/main.go#L317-L319) and [doc](https://pkg.go.dev/net#Listen)). I was wondering if I should split off the port part into `EXTERNAL_HOST_PORT` in order to be able to use `ENV[EXTERNAL_HOST]` in `EXPECT_METRICS_EXIST`. However this would require me to change a lot of other tests which assume that `EXTERNAL_HOST` has the port number included. Thoughts?

File: daemon/cmd/integration_runner/main.go (hunk 1 above)
Comment (lavarou) [reply daemon/cmd/integration_runner/main.go:378]: Setting `ctx.Env["EXTERNAL_HOST"]` is not enough for `EXTERNAL_HOST` the env var to be available in the runtime environment for `os.Getenv`, used in [`SubEnvVars`](https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/daemon/internal/newrelic/integration/test.go#L291), to find it.

File: tests/integration/external/guzzle6/test_timeout_async.php (hunk 2 above)
Comment (mfulb) [reply tests/integration/external/guzzle6/test_timeout_async.php:24]: That is another consideration - I'm more wondering if `EXTERNAL_HOST` is actually "127.0.0.1" in all cases or not - and if the "127.0.0.1" in the metric line might not need to have an env substitution as well?  Also should the IP/host in the metric always be the same as in the `http.url`?

File: daemon/cmd/integration_runner/main.go (hunk 1 above)
Comment (mfulb) [reply daemon/cmd/integration_runner/main.go:378]: The code appears to associate the `ctx.Env` with each test run and is used as the env for the PHP which is spawned.

File: daemon/cmd/integration_runner/main.go [hunk 3]
```diff
@@ -245,6 +245,16 @@ func catRequest(w http.ResponseWriter, r *http.Request) {
 	w.Write(body)
 }
 
+func delayRequest(w http.ResponseWriter, r *http.Request) {
+	duration := r.URL.Query().Get("duration")
+	io.WriteString(w, "waiting...")
```
Comment (mfulb) [inline daemon/cmd/integration_runner/main.go:250]: Is this output necessary?

Comment (lavarou) [reply daemon/cmd/integration_runner/main.go:250]: It is not required for the guzzle tests.

File: tests/integration/external/guzzle6/test_timeout_async.php (hunk 2 above)
Comment (lavarou) [reply tests/integration/external/guzzle6/test_timeout_async.php:24]: > I'm more wondering if `EXTERNAL_HOST` is actually "127.0.0.1" in all cases or not - and if the "127.0.0.1" in the metric line might not need to have an env substitution as well?

It is not always 127.0.0.1: https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/tests/integration/external/guzzle7/test_transfer_exception_sync.php#L25

It is 127.0.0.1 for tests that make requests to endpoints exposed by `integration_runner`.

Comment (lavarou) [reply tests/integration/external/guzzle6/test_timeout_async.php:24]: Moreover, there are other tests that have 127.0.0.1 hardcoded in names but don't test "http.url" attributes. E.g.: https://github.com/newrelic/newrelic-php-agent/blob/55ab2076d11456cef2aed9d39f5bd87885679473/tests/integration/external/curl_exec/test_dt_correct_span_is_external.php#L69.

File: daemon/cmd/integration_runner/main.go (hunk 3 above)
Comment (mfulb) [reply daemon/cmd/integration_runner/main.go:250]:
```suggestion
	io.WriteString(w, "waiting...")
```

Comment (mfulb) [reply daemon/cmd/integration_runner/main.go:250]: That suggestion is reasonable?

File: daemon/cmd/integration_runner/main.go (hunk 1 above)
Comment (mfulb) [reply daemon/cmd/integration_runner/main.go:378]: It seems currently the `ctx.Env` is not included in the variables the `SubEnvVar` considers.  That might be an enhancement that would remove the need to make this addition.

Comment (lavarou) [reply daemon/cmd/integration_runner/main.go]: @mfulb 800b45a43ae46043ecdf1f1f0692de7af3fff4ed was needed for `ctx.Env` to be available to env var substitution.

Comment (lavarou) [reply daemon/cmd/integration_runner/main.go]: @mfulb https://github.com/newrelic/newrelic-php-agent/commit/800b45a43ae46043ecdf1f1f0692de7af3fff4ed wasn't enough - `Test.Env` still didn't have env vars available to PHP. I had to do this: https://github.com/newrelic/newrelic-php-agent/pull/883/commits/e20f4b93b4e7bca34327ab2c8680cf59b84ad9b5. 5e111d2374a53e4383e713cd932e667b0c456fd3 showcases how this works.

File: tests/integration/external/guzzle6/test_timeout_async.php (hunk 2 above)
Comment (mfulb) [reply tests/integration/external/guzzle6/test_timeout_async.php:24]: Thank you for exploring this further.   I'm happy with your explanation.

File: daemon/cmd/integration_runner/main.go (hunk 3 above)
Comment (mfulb) [reply daemon/cmd/integration_runner/main.go:250]: After discussion it was clarified for me this output appears in the body of the response from the `/delay` endpoint and not to the console and so I am not asking for any changes.

File: daemon/internal/newrelic/integration/test.go [hunk 4]
```diff
@@ -200,35 +200,39 @@ func merge(a, b map[string]string) map[string]string {
 }
 
 func (t *Test) MakeRun(ctx *Context) (Tx, error) {
-	env := merge(ctx.Env, t.Env)
+	for k, v := range ctx.Env {
```
Comment (mfulb) [inline daemon/internal/newrelic/integration/test.go:203]: The `merge()` call in the previous code would give values in `t.Env` precedence over values in `ctx.Env`.  This new code does the opposite.
My suggestion would be to call `merge()` as before and store the result in `t.Env` to ensure  operation is the same as previously.

File: daemon/internal/newrelic/integration/test.go [hunk 5]
```diff
@@ -285,10 +289,15 @@ func ScrubHost(in []byte) []byte {
 	return re.ReplaceAll(in, []byte("__HOST__"))
 }
 
-func SubEnvVars(in []byte) []byte {
+func (t *Test) subEnvVars(in []byte) []byte {
 	re := regexp.MustCompile("ENV\\[.*?\\]")
 	return re.ReplaceAllFunc(in, func(match []byte) []byte {
-		return []byte(os.Getenv(string(match[4 : len(match)-1])))
+		k := string(match[4 : len(match)-1])
+		v, present := os.LookupEnv(k)
```
Comment (mfulb) [inline daemon/internal/newrelic/integration/test.go:296]: This appears to give the OS environment values precedence over `t.Env` when substitution occurs?  Is this desired or is it better to let the `/*ENVIRONMENT*/` values be able to override the OS environment?

File: daemon/internal/newrelic/integration/test.go (hunk 4 above)
Comment (lavarou) [reply daemon/internal/newrelic/integration/test.go]: @mfulb How about 5064b7c93267fae793fbef33760b1df37fc35d77?

File: daemon/internal/newrelic/integration/test.go (hunk 5 above)
Comment (lavarou) [reply daemon/internal/newrelic/integration/test.go:301]: @mfulb Very good point! I think values from `/*ENVIRONMENT*/` directive should take precedence over OS environment. How about https://github.com/newrelic/newrelic-php-agent/commit/5064b7c93267fae793fbef33760b1df37fc35d77?

File: daemon/cmd/integration_runner/main.go (hunk 1 above)
Comment (lavarou) [reply daemon/cmd/integration_runner/main.go]: And possibly the last patch: 5064b7c93267fae793fbef33760b1df37fc35d77, which ensures that values from `/*ENVIRONMENT*/` directive take precedence over OS environment.

File: daemon/internal/newrelic/integration/test.go [hunk 6]
```diff
@@ -285,10 +289,15 @@ func ScrubHost(in []byte) []byte {
...
+		if !present {
+			v = t.Env[k]
```
Comment (mfulb) [inline daemon/internal/newrelic/integration/test.go]: What happens if the key is not in in or the process environment variables? Does this return nil?

File: daemon/internal/newrelic/integration/test.go [hunk 7]
```diff
@@ -285,10 +285,15 @@ func ScrubHost(in []byte) []byte {
...
+func (t *Test) subEnvVars(in []byte) []byte {
 	re := regexp.MustCompile("ENV\\[.*?\\]")
 	return re.ReplaceAllFunc(in, func(match []byte) []byte {
-		return []byte(os.Getenv(string(match[4 : len(match)-1])))
+		k := string(match[4 : len(match)-1])
+		v, present := t.Env[k]
+		if !present {
+			v = os.Getenv(k)
+		}
+		return []byte(v)
```
Comment (mfulb) [inline daemon/internal/newrelic/integration/test.go:296]: What happens if the key is not in in or the process environment variables? Does this return nil?

Comment (lavarou) [reply daemon/internal/newrelic/integration/test.go:296]: If `t.Env` doesn't have the value assigned to `k`, and `k` is not defined in the environment, `v` will be empty - `""`.

More info at: https://go.dev/ref/spec#Index_expressions, https://pkg.go.dev/os#Getenv, https://go.dev/blog/maps

Comment (lavarou) [reply daemon/internal/newrelic/integration/test.go:296]: I have added a test to illustrate this: 5a8e3f4046fe427d329e49ac3faddc9da34b8e6c.

**Review by mfulb — APPROVED** [review]
Really nice work Michal - this is a great PR!

File: agent/lib_guzzle6.c [hunk 8]
```diff
@@ -468,8 +468,16 @@ void nr_guzzle6_enable(TSRMLS_D) {
        */
       "      $rh = new RequestHandler($request);"
       "      $promise = $handler($request, $options);"
-      "      $promise->then([$rh, 'onFulfilled'], [$rh, 'onRejected']);"
-
+      "      if (PromiseInterface::REJECTED == $promise->getState()) {"
+      /*
+                Special case for sync request. When sync requests is rejected,
```
Comment (zsistla) [inline agent/lib_guzzle6.c:473]:
```suggestion
                Special case for sync request. When sync request is rejected,
```

File: tests/integration/external/guzzle6/test_transfer_exception_sync.php [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+    new \GuzzleHttp\Exception\TransferException()
+  ]));
+
+$client = new GuzzleHttp\Client([
+  'handler' => $stack,
+]);
+
+try {
+  $response = $client->send($request);
+} catch (\GuzzleHttp\Exception\TransferException $e) {
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_transfer_exception_sync.php:86]: In the tests that throw exceptions, could we have versions where the exception isn't caught to verify the exception is also recorded correctly?

File: tests/integration/external/guzzle6/test_transfer_exception_async.php [hunk 10]
```diff
@@ -0,0 +1,86 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing exception other than BadResponseException
+is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_transfer_exception_async.php:9]:
```suggestion
is marked as http and uri is captured. Status code is marked as 0 since there was no response.
```

File: tests/integration/external/guzzle6/test_timeout_async.php [hunk 11]
```diff
@@ -0,0 +1,67 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that times out is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_timeout_async.php:8]:
```suggestion
Test that the span for an async external request that times out is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle6/test_bad_response_exception_async.php [hunk 12]
```diff
@@ -0,0 +1,92 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing BadResponseException exception
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_bad_response_exception_async.php:8]: copy/paste comment for all tests: `reqest` should be `request`

File: tests/integration/external/guzzle6/test_timeout_sync.php [hunk 13]
```diff
@@ -0,0 +1,67 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an sync external reqest that times out is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_timeout_sync.php:8]:
```suggestion
Test that the span for an sync external request that times out is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle6/test_transfer_exception_sync.php [hunk 14]
```diff
@@ -0,0 +1,90 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing exception other than BadResponseException
+is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle6/test_transfer_exception_sync.php:9]:
```suggestion
is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle7/test_timeout_async.php [hunk 15]
```diff
@@ -0,0 +1,67 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that times out is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle7/test_timeout_async.php:8]:
```suggestion
Test that the span for an async external request that times out is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle7/test_timeout_sync.php [hunk 16]
```diff
@@ -0,0 +1,67 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an sync external reqest that times out is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle7/test_timeout_sync.php:8]:
```suggestion
Test that the span for an sync external request that times out is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle7/test_transfer_exception_async.php [hunk 17]
```diff
@@ -0,0 +1,86 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing exception other than BadResponseException
+is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle7/test_transfer_exception_async.php:9]:
```suggestion
is marked as http and uri is captured. Status code is marked as 0.
```

File: tests/integration/external/guzzle7/test_transfer_exception_sync.php [hunk 18]
```diff
@@ -0,0 +1,90 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing exception other than BadResponseException
+is marked as http and uri is captured.
```
Comment (zsistla) [inline tests/integration/external/guzzle7/test_transfer_exception_sync.php:9]:
```suggestion
is marked as http and uri is captured. Status code is marked as 0.
```

**Comment by zsistla** [comment]
Really nicely done!  Thanks for addressing this issue.

Couple of tests comments, but otherwise, LGTM.

File: tests/integration/external/guzzle6/test_bad_response_exception_async.php (hunk 12 above)
Comment (lavarou) [inline tests/integration/external/guzzle6/test_bad_response_exception_async.php:8]:
```suggestion
Test that the span for an async external request that ends up throwing BadResponseException exception
```

File: tests/integration/external/guzzle6/test_bad_response_exception_sync.php [hunk 19]
```diff
@@ -0,0 +1,96 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing BadResponseException exception
```
Comment (lavarou) [inline tests/integration/external/guzzle6/test_bad_response_exception_sync.php:8]:
```suggestion
Test that the span for a sync external request that ends up throwing BadResponseException exception
```

File: tests/integration/external/guzzle6/test_transfer_exception_async.php [hunk 20]
```diff
@@ -0,0 +1,86 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing exception other than BadResponseException
```
Comment (lavarou) [inline tests/integration/external/guzzle6/test_transfer_exception_async.php:8]:
```suggestion
Test that the span for an async external request that ends up throwing exception other than BadResponseException
```

File: tests/integration/external/guzzle6/test_transfer_exception_sync.php [hunk 21]
```diff
@@ -0,0 +1,90 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing exception other than BadResponseException
```
Comment (lavarou) [inline tests/integration/external/guzzle6/test_transfer_exception_sync.php:8]:
```suggestion
Test that the span for a sync external request that ends up throwing exception other than BadResponseException
```

File: tests/integration/external/guzzle7/test_bad_response_exception_async.php [hunk 22]
```diff
@@ -0,0 +1,92 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing BadResponseException exception
```
Comment (lavarou) [inline tests/integration/external/guzzle7/test_bad_response_exception_async.php:8]:
```suggestion
Test that the span for an async external request that ends up throwing BadResponseException exception
```

File: tests/integration/external/guzzle7/test_bad_response_exception_sync.php [hunk 23]
```diff
@@ -0,0 +1,96 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing BadResponseException exception
```
Comment (lavarou) [inline tests/integration/external/guzzle7/test_bad_response_exception_sync.php:8]:
```suggestion
Test that the span for a sync external request that ends up throwing BadResponseException exception
```

File: tests/integration/external/guzzle7/test_transfer_exception_async.php [hunk 24]
```diff
@@ -0,0 +1,86 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for an async external reqest that ends up throwing exception other than BadResponseException
```
Comment (lavarou) [inline tests/integration/external/guzzle7/test_transfer_exception_async.php:8]:
```suggestion
Test that the span for an async external request that ends up throwing exception other than BadResponseException
```

File: tests/integration/external/guzzle7/test_transfer_exception_sync.php [hunk 25]
```diff
@@ -0,0 +1,90 @@
+<?php
+/*
+ * Copyright 2020 New Relic Corporation. All rights reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/*DESCRIPTION
+Test that the span for a sync external reqest that ends up throwing exception other than BadResponseException
```
Comment (lavarou) [inline tests/integration/external/guzzle7/test_transfer_exception_sync.php:8]:
```suggestion
Test that the span for a sync external request that ends up throwing exception other than BadResponseException
```

File: tests/integration/external/guzzle6/test_transfer_exception_sync.php (hunk 9 above)
Comment (lavarou) [reply tests/integration/external/guzzle6/test_transfer_exception_sync.php:86]: @zsistla Although exception handling is a different feature in the agent, I added a couple of tests which demonstrate that Guzzle's instrumentation doesn't affect agent's ability to record errors for uncaught exceptions. Is bed374a611dd7df68af857eb8e284b624f933f66 sufficient?

Comment (zsistla) [reply tests/integration/external/guzzle6/test_transfer_exception_sync.php:86]: Since we're creating the external span and guzzle is a special case with our middleware, it's good to check that errors are properly added for the two exception paths (BadResponseException and other)we cover here.
Thanks for adding the tests for guzzle7, they look good!  Can they be added for guzzle6 as well?

File: tests/integration/external/guzzle6/test_bad_response_exception_async.php (hunk 12 above)
Comment (lavarou) [reply tests/integration/external/guzzle6/test_bad_response_exception_async.php]: Addressed in 13db0365f685a2a186d570757fee9dc15a7fdfd8.

File: tests/integration/external/guzzle6/test_transfer_exception_sync.php (hunk 9 above)
Comment (lavarou) [reply tests/integration/external/guzzle6/test_transfer_exception_sync.php:86]: @zsistla Added in 0af94988bbfc48a010089a6b23d19a5efcd5e84f. 

Side note: Guzzle 6 is no longer supported by Guzzle. It reached its EOL on 2023-10-31 - see [Guzzle version guidance](https://github.com/guzzle/guzzle?tab=readme-ov-file#version-guidance).
